version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: photo_browser
      POSTGRES_USER: photo_user
      POSTGRES_PASSWORD: photo_pass
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

